feat: Add linkcheck to build docs workflow (#249)
Signed-off-by: Charlie Truong <chtruong@nvidia.com>

diff --git a/.github/workflows/_build_docs.yml b/.github/workflows/_build_docs.yml
--- a/.github/workflows/_build_docs.yml
+++ b/.github/workflows/_build_docs.yml
@@ -34,6 +34,71 @@ jobs:
           cd docs
           uv run --only-group docs sphinx-build --fail-on-warning --builder html . _build/html
 
+      - name: Sphinx linkcheck
+        run: |
+          cd docs
+          uv run --only-group docs sphinx-build --builder linkcheck . _build/linkcheck || true
+
+      - name: Eliminate false positives
+        run: |
+          FALSE_POSITIVES_JSON=docs/false_positives.json
+          NEEDS_REVIEW_JSON=docs/links_needing_review.json
+          LINKCHECK_JSON=docs/_build/linkcheck/output.json
+
+          function check_environment {
+            local err=0
+            if ! [ -x "$(command -v jq)" ]; then
+              >&2 echo "jq is required but is not found."
+              ((err++))
+            fi
+            if [ ! -f "${LINKCHECK_JSON}" ]; then
+              >&2 echo "Did not find linkcheck output JSON file: ${LINKCHECK_JSON}."
+              >&2 echo "Run Sphinx with the linkcheck arg: make -C docs clean linkcheck"
+              ((err++))
+            fi
+            if [ "${err}" -gt 0 ]; then
+              exit 2
+            fi
+          }
+
+          function check_links {
+            local err=0
+            broken=$(jq -s 'map(select(.status=="broken"))' "$LINKCHECK_JSON")
+            count=$(echo "${broken}" | jq 'length')
+            for i in $(seq 0 $(($count - 1)))
+            do
+              entry=$(echo "${broken}" | jq ".[${i}]")
+              link=$(echo "${entry}" | jq -r '.uri')
+              [ -n "${DEBUG}" ] && {
+              echo >&2 "Checking for false positive: ${link}"
+              }
+              local false_positive_resp="false"
+              local needs_review_resp="false"
+              if [ -f "${FALSE_POSITIVES_JSON}" ]; then
+                false_positive_resp=$(jq --arg check "${link}" -s 'any(.uri == $check)' < "${FALSE_POSITIVES_JSON}")
+              fi
+              if [ -f "${NEEDS_REVIEW_JSON}" ]; then
+                needs_review_resp=$(jq --arg check "${link}" -s 'any(.uri == $check)' < "${NEEDS_REVIEW_JSON}")
+              fi
+              # "false" indicates that the URL did not match any of the URIs in the false positive file.
+              if [[ "false" = "${false_positive_resp}" && "false" = "${needs_review_resp}" ]]; then
+                ((err++))
+                echo "${entry}"
+              fi
+            done
+            exit "${err}"
+          }
+
+          check_environment
+          check_links
+
+      - name: Upload linkcheck output
+        uses: actions/upload-artifact@v4
+        with:
+          name: linkcheck-artifact
+          path: docs/_build/linkcheck
+          retention-days: 7
+
       - name: Upload docs as artifact
         uses: actions/upload-artifact@v4
         with:
